# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Pipeline javaConsole

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Compilando
      run: javac src/Main.java
      
    - name: Executar
      run: java src/Main.java
      
    - uses: mr-smithers-excellent/docker-build-push@v6
    
    - name: Build & push Docker image
      with:
        image: samirasouza/image_java_console
        tags: v1, 1.0
        registry: docker-url.io
        dockerfile: Dockerfile.ci
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

